get:
  tags:
    - deployment
    - identification
  summary: Get deployment status and version of a containerized application
  description: |-
    The currently active containerized application version `current` is read from the target's filesystem, 
    more specifically from the application manifest/.env file, which must contain a SOFTWARE_VERSION variable.

    `deploy_status.code` reflects the status of the latest application update deployment:
    - waiting: deployment not yet started, waiting for other updates to finish
    - already_deployed: the same application version is already deployed
    - in_progress: deployment is currently in progress
    - success: deployment completed successfully
    - failure: deployment failed

    `deploy_status.message` may contain additional information about the deployment status, e.g. error messages in case of failure.
  parameters:
    - name: applicationname
      in: path
      required: true
      description: Name of the application
      schema:
        type: string
        example: nginx-demo
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../../core-api-server.yml#/components/schemas/EntityStatus"
    "400":
      $ref: "../../responses/bad_request.yml"
    "500":
      $ref: "../../responses/internal_server_error.yml"

put:
  tags:
    - deployment
  summary: Load containerized application
  description: |-
    Start containerized application update on the device. Supply a `.mender` file containing the application.
    
    The API returns immediately after the update process is started. Call
    GET /software/application/{applicationname} to check deployment status.

    If there is already an application update for that application name in progress, 
    the API returns a 412 Precondition Failed error.

    If the supplied artifact is invalid, the API returns a 400 Bad Request error.

    If the same application version is already deployed, the API returns a 409 Conflict error.

    If there is a core OS or other application update in progress, the application update is 
    deferred until the core OS update is finished. Status 202 Accepted is returned in this case.

    If the update installation succeeds, the new application version will be active without requiring a reboot.
    Note that there is no rollback mechanism for application updates, so if the new application version fails to start, 
    the device will be left without a running instance of that application.

  parameters:
    - name: applicationname
      in: path
      required: true
      description: Name of the application to update
      schema:
        type: string
        example: nginx-demo
  requestBody:
    required: true
    content:
      application/octet-stream:
        schema:
          type: string
          format: binary
  responses:
    "202":
      description: Accepted, application update started
    "400":
      $ref: "../../responses/bad_request.yml"
    "409":
      $ref: "../../responses/conflict.yml"
    "412":
      $ref: "../../responses/precondition_failed.yml"
    "500":
      $ref: "../../responses/internal_server_error.yml"
